server.port: 8001

spring.data.mongodb:
  host: localhost
  port: 27017
  database: developer-db

logging:
  level:
    root: INFO
    com.devhubsocial: DEBUG
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
---
spring.profiles: docker

spring.data.mongodb.host: mongodb

server.port: 8080
